[package]
name = "accesskit_multi_tree"
version = "0.1.0"
edition = "2024"

[dependencies]
accesskit = "0.21.1"
accesskit_winit = "0.29.2"

[dependencies.winit]
version = "0.30.5"
default-features = false

[dev-dependencies.winit]
version = "0.30.5"
features = [
    "x11",
    "wayland",
    "wayland-dlopen",
    "wayland-csd-adwaita",
]
default-features = false
